#!/bin/bash

aws ecr get-login-password --region eu-north-1 --profile odin-cdk| docker login --username AWS --password-stdin 991049544436.dkr.ecr.eu-north-1.amazonaws.com

docker build --build-arg FM=1 --build-arg INVMODE=stnd -t 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:stnd1 .
docker build --build-arg FM=2 --build-arg INVMODE=stnd -t 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:stnd2 .
docker build --build-arg FM=8 --build-arg INVMODE=stnd -t 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:stnd8 .
docker build --build-arg FM=17 --build-arg INVMODE=stnd -t 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:stnd17 .
docker build --build-arg FM=13 --build-arg INVMODE=meso -t 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:meso13 .
docker build --build-arg FM=14 --build-arg INVMODE=meso -t 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:meso14 .
docker build --build-arg FM=19 --build-arg INVMODE=meso -t 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:meso19 .
docker build --build-arg FM=21 --build-arg INVMODE=meso -t 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:meso21 .
docker build --build-arg FM=22 --build-arg INVMODE=meso -t 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:meso22 .
docker build --build-arg FM=24 --build-arg INVMODE=meso -t 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:meso24 .

docker push 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:stnd1
docker push 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:stnd2
docker push 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:stnd8
docker push 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:stnd17
docker push 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:meso13
docker push 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:meso14
docker push 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:meso19
docker push 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:meso21
docker push 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:meso22
docker push 991049544436.dkr.ecr.eu-north-1.amazonaws.com/qsmr:meso24

aws ecs update-service --profile odin-cdk --cluster OdinApiCluster --service QSMR-stnd1 --force-new-deployment --no-cli-pager
aws ecs update-service --profile odin-cdk --cluster OdinApiCluster --service QSMR-stnd2 --force-new-deployment --no-cli-pager
aws ecs update-service --profile odin-cdk --cluster OdinApiCluster --service QSMR-stnd8 --force-new-deployment --no-cli-pager
aws ecs update-service --profile odin-cdk --cluster OdinApiCluster --service QSMR-stnd17 --force-new-deployment --no-cli-pager
aws ecs update-service --profile odin-cdk --cluster OdinApiCluster --service QSMR-meso13 --force-new-deployment --no-cli-pager
aws ecs update-service --profile odin-cdk --cluster OdinApiCluster --service QSMR-meso14 --force-new-deployment --no-cli-pager
aws ecs update-service --profile odin-cdk --cluster OdinApiCluster --service QSMR-meso19 --force-new-deployment --no-cli-pager
aws ecs update-service --profile odin-cdk --cluster OdinApiCluster --service QSMR-meso21 --force-new-deployment --no-cli-pager
aws ecs update-service --profile odin-cdk --cluster OdinApiCluster --service QSMR-meso22 --force-new-deployment --no-cli-pager
aws ecs update-service --profile odin-cdk --cluster OdinApiCluster --service QSMR-meso24 --force-new-deployment --no-cli-pager
