[project]
name = "qsmr-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.17",
    "pandas>=2.3.3",
    "pyarrow>=22.0.0",
    "pydantic>=2.12.5",
    "pydantic-mongo>=3.1.0",
    "pyhumps>=3.8.0",
]

[build-system]
requires = ["uv-build>=0.1.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "black>=25.12.0",
    "boto3-stubs[s3,sqs]>=1.42.17",
    "ipykernel>=7.1.0",
    "mypy>=1.19.1",
    "openapi-python-client>=0.28.0",
    "pandas-stubs>=2.3.3.251201",
    "pytest>=9.0.2",
    "ruff>=0.14.10",
]

[pytest]
markers = ["system"]
